version: "3.9"
services:

  task_server:
    build: .
    volumes:
      - .:/letsplaycastleclash

    environment:
      PYTHONUNBUFFERED: 1
      TZ: Europe/Moscow

    restart: always

    ports:
      - "8055:8055"

    command: python3 main.py